name: Java Workflow

on: 
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'
      - name: Build and Test with maven
        run: mvn -B clean verify
        
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: check style
        run: mvn checkstyle:check
        
      - name: Archive linter results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linter-results
          path: target/checkstyle-result.xml
